- platform: template
  switches:
    party:
      value_template: "{{ states('input_boolean.party') }}"
      friendly_name: La Festa
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.party
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.party
