- platform: history_stats
  name: Küche Licht Laufzeit (Heute)
  entity_id: light.kueche_licht
  state: "on"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: Küche Licht Laufzeit (Monat) # month
  entity_id: light.kueche_licht
  state: "on"
  type: time
  start: "{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"
