# reference: https://www.home-assistant.io/integrations/filesize/

# - platform: filesize
#   file_paths:
#     - /config/home-assistant_v2.db #/var/lib/homeassistant/.homeassistant/home-assistant_v2.db
#     - /config/music_assistant.db
#     - /config/zigbee.db #zha
#     - /config/addons_config/double-take/database.db
#     - /config/addons_config/tandoor_recipes/recipes.db
#     - /config/zigbee2mqtt/database.db
#     - /media/frigate/frigate.db

- platform: filesize
  sensors:
    hassos_db_size:
      friendly_name: HassOS Datenbankgröße
      file_paths:
        - /config/home-assistant_v2.db #/var/lib/homeassistant/.homeassistant/home-assistant_v2.db
    mass_db_size:
      friendly_name: Musik Assistant Datenbankgröße
      file_paths:
        - /config/music_assistant.db


### MARIA DB SIZE ##############################################################
- platform: sql
  db_url: !secret hass_db_url
  queries:
    - name: MariaDB DB Größe
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: GB