- platform: powercalc
  name: Abstellkammer Licht Strom
  unique_id: abstellkammer_licht_power
  entity_id: light.abstellkammer_licht
  linear:
    min_power: 0.5
    max_power: 6.5
  #fixed:
  #  power: 6.5
  energy_integration_method: left
