- platform: powercalc
  name: Wohnzimmer Licht Strom
  unique_id: wohnzimmer_licht_power
  entity_id: light.wohnzimmer_licht
  linear:
    min_power: 1
    max_power: 20
  #fixed:
  #  power: 22
  energy_integration_method: left
