# Calculate the difference between inside and outside temperature

- platform: template
  sensors:
    temperature_difference_in_out:
      friendly_name: Temperaturdifferenz zur Außenwelt
      device_class: temperature
      unit_of_measurement: !secret unit_temperature_str
      value_template: >-
        {% if is_state('weather.dwd_weather_offenbach', 'unknown') %}
          Unbekannt
        {% else %}
          {{ ( states('sensor.wohnungs_temperatur') | float - states_attr('weather.dwd_weather_offenbach', 'temperature') | float ) | round(1) }}
        {% endif %}
