# calculate estimated room temperature

- platform: template
  sensors:
    temperature_window_wohnzimmer:
      friendly_name: Wohnzimmer Fenster Temperatur
      unique_id: wohnzimmer_fenster_temperatur
      unit_of_measurement: !secret unit_temperature_str
      value_template: "{{ state_attr('binary_sensor.wohnzimmer_fenster', 'temperature') | float  }} "
      device_class: temperature
    temperature_window_kuche:
      friendly_name: Küche Fenster Temperatur
      unique_id: kueche_fenster_temperatur
      unit_of_measurement: !secret unit_temperature_str
      value_template: "{{ state_attr('binary_sensor.kueche_fenster', 'temperature') | float  }} "
      device_class: temperature
    temperature_window_alfi_klein:
      friendly_name: Alfi Fenster Klein Temperatur
      unique_id: alfi_fenster_klein_temperatur
      unit_of_measurement: !secret unit_temperature_str
      value_template: "{{ state_attr('binary_sensor.alfi_fenster_klein', 'temperature') | float  }} "
      device_class: temperature
    temperature_window_alfi_gross:
      friendly_name: Alfi Fenster Groß Temperatur
      unique_id: alfi_fenster_gross_temperatur
      unit_of_measurement: !secret unit_temperature_str
      value_template: "{{ state_attr('binary_sensor.alfi_fenster_gross', 'temperature') | float  }} "
      device_class: temperature
    temperature_window_badezimmer_klein:
      friendly_name: Badezimmer Fenster Klein Temperatur
      unique_id: badezimmer_fenster_klein_temperatur
      unit_of_measurement: !secret unit_temperature_str
      value_template: "{{ state_attr('binary_sensor.badezimmer_fenster_klein', 'temperature') | float  }} "
      device_class: temperature
    temperature_window_badezimmer_gross:
      friendly_name: Badezimmer Fenster Groß Temperatur
      unique_id: badezimmer_fenster_gross_temperatur
      unit_of_measurement: !secret unit_temperature_str
      value_template: "{{ state_attr('binary_sensor.badezimmer_fenster_gross', 'temperature') | float  }} "
      device_class: temperature
    temperature_window_sebi_klein:
      friendly_name: Sebi Fenster Klein Temperatur
      unique_id: sebi_fenster_klein_temperatur
      unit_of_measurement: !secret unit_temperature_str
      value_template: "{{ state_attr('binary_sensor.sebi_fenster_klein', 'temperature') | float  }} "
      device_class: temperature
    temperature_window_sebi_gross:
      friendly_name: Sebi Fenster Groß Temperatur
      unique_id: sebi_fenster_gross_temperatur
      unit_of_measurement: !secret unit_temperature_str
      value_template: "{{ state_attr('binary_sensor.sebi_fenster_gross', 'temperature') | float  }} "
      device_class: temperature
