###
# NASA API collection
#
# Get API Token at: https://api.nasa.gov/index.html
###

# API APOD: NASA Astronomical Picture of the Day
sensor:
  - platform: rest
    resource: https://api.nasa.gov/planetary/apod
    name: nasa_apod
    value_template: "OK"
    params:
      api_key: !secret api_key_nasa
      thumbs: true
    json_attributes:
      - date
      - title
      - explanation
      - url
      - thumbnail_url
      - media_type

homeassistant:
  customize:
    sensor.nasa_apod:
      friendly_name: Astronomisches Bild des Tages
      icon: mdi:image
  
###
# Clear recorder
###

recorder:
  exclude:
    entities:
      - sensor.nasa_apod