# ##########################################################################################
# # Inputs
# ##########################################################################################

input_boolean:
  sebi_party:
    name: Sebi Partymodus
    icon: mdi:PartyPopper
    initial: off
    
    
input_number:
  sebi_party_speed:
    name: Sebi Party Speed
    initial: 0.4
    min: 0.1
    max: 0.9
    step: 0.1
    
# ##########################################################################################
# # Inputs
# ##########################################################################################

    
switch:
  - platform: template
    switches:
      party:
        value_template: '{{ states("input_boolean.party") }}'
        friendly_name: 'Sebi Partymodus'
        turn_on:
          - service: input_boolean.turn_on
            entity_id: input_boolean.sebi_party
        turn_off:
          - service: input_boolean.turn_off
            entity_id: input_boolean.sebi_party

##########################################################################################
# Scripts
##########################################################################################
script:
  sebi_lights_partying_on:
    alias: "[Home] - Sebi Lichter Party an"
    sequence:
      - service: scene.create
        data:
          scene_id: sebiprimaparty
          snapshot_entities:
          - light.sebi_licht
          - light.sebi_stimmungslicht
      - service: script.turn_on
        entity_id: script.sebi_lights_partying

  sebi_lights_partying:
    sequence:
      - repeat:
          while:
            - condition: state
              entity_id: input_boolean.sebi_party
              state: 'on'
          sequence:
            - service: light.turn_on
              data_template:
                entity_id: light.sebi_licht
                rgb_color: ['{{ (range(0, 255)|random) }}',
                            '{{ (range(0, 255)|random) }}',
                            '{{ (range(0, 255)|random) }}']
                brightness: 250
                transition: '{{ (range(1, 3)|random) }}'
            - service: light.turn_on
              data_template:
                entity_id: light.sebi_stimmungslicht
                rgb_color: ['{{ (range(0, 255)|random) }}',
                            '{{ (range(0, 255)|random) }}',
                            '{{ (range(0, 255)|random) }}']
                brightness: 250
                transition: '{{ (range(1, 3)|random) }}'
            - delay: "{{ states.input_number.sebi_party_speed.state }}"

  sebi_lights_partying_off:
    #alias: Lichter party aus
    sequence:
      - service: scene.turn_on
        data:
          entity_id: scene.studioprimaparty


##########################################################################################
# Automations
##########################################################################################

automation:
  - alias: "[Home] - Sebi Lichter Party an"
    id: "Sebi Party ON"
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.sebi_party
        from: 'off'
        to: 'on'
    action: 
      service: script.sebi_lights_partying_on

  - alias: "[Home] - Sebi Lichter Party aus"
    id: 'Sebi Party OFF'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.sebi_party
        from: 'on'
        to: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.sebi_licht
          - light.sebi_stimmungslicht
      - delay: 1
      - service: script.sebi_lights_partying_off```