# ##########################################################################################
# # Inputs
# ##########################################################################################

input_boolean:
  wohnzimmer_party:
    name: Wohnzimmer Partymodus
    icon: mdi:PartyPopper
    initial: off
    
    
input_number:
  wohnzimmer_party_speed:
    name: Wohnzimmer Party Speed
    initial: 0.4
    min: 0.1
    max: 0.9
    step: 0.1
    
# ##########################################################################################
# # Inputs
# ##########################################################################################

    
switch:
  - platform: template
    switches:
      party:
        value_template: '{{ states("input_boolean.party") }}'
        friendly_name: 'Wohnzimmer Partymodus'
        turn_on:
          - service: input_boolean.turn_on
            entity_id: input_boolean.wohnzimmer_party
        turn_off:
          - service: input_boolean.turn_off
            entity_id: input_boolean.wohnzimmer_party

##########################################################################################
# Scripts
##########################################################################################
script:
  wohnzimmer_lights_partying_on:
    alias: "[Home] - Wohnzimmerlichter Party an"
    sequence:
      - service: scene.create
        data:
          scene_id: studioprimaparty
          snapshot_entities:
          - light.wohnzimmer_licht
      - service: script.turn_on
        entity_id: script.wohnzimmer_lights_partying

  wohnzimmer_lights_partying:
    sequence:
      - repeat:
          while:
            - condition: state
              entity_id: input_boolean.wohnzimmer_party
              state: 'on'
          sequence:
            - service: light.turn_on
              data_template:
                entity_id: light.wohnzimmer_licht
                rgb_color: ['{{ (range(0, 255)|random) }}',
                            '{{ (range(0, 255)|random) }}',
                            '{{ (range(0, 255)|random) }}']
                brightness: 250
                transition: '{{ (range(1, 3)|random) }}'
            - delay: "{{ states.input_number.wohnzimmer_party_speed.state }}"

  wohnzimmer_lights_partying_off:
    #alias: Lichter party aus
    sequence:
      - service: scene.turn_on
        data:
          entity_id: scene.studioprimaparty


##########################################################################################
# Automations
##########################################################################################

automation:
  - alias: "[Home] - Wohnzimmerlichter Party an"
    id: 'Wohnzimmer Party ON'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.wohnzimmer_party
        from: 'off'
        to: 'on'
    action: 
      service: script.wohnzimmer_lights_partying_on

  - alias: "[Home] - Wohnzimmerlichter Party aus"
    id: 'Wohnzimmer Party OFF'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.wohnzimmer_party
        from: 'on'
        to: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.wohnzimmer_licht
      - delay: 1
      - service: script.wohnzimmer_lights_partying_off```