input_boolean:
  zigbee_permit_join:
    name: "Ger채te d체rfen beitreten"
    initial: off
    icon: mdi:cellphone-wireless

timer:
  zigbee_permit_join:
    name: "Zeit 체brig"
    duration: 300

mqtt:
  sensor:
    - name: "Zigbee Br체cken-Status"
      unique_id: zigbee_bridge_state
      state_topic: "zigbee2mqtt/bridge/state"
      icon: mdi:router-wireless
      #device_class: "connectivity"

automation:
  - id: enable_zigbee_join
    alias: "[System] - Aktiviere Zigbee Beitritt"
    trigger:
      - platform: state
        entity_id: input_boolean.zigbee_permit_join
        to: 'on'
    action:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/bridge/config/permit_join
          payload: 'true'
      - service: timer.start
        data:
          entity_id: timer.zigbee_permit_join

  - id: disable_zigbee_join
    alias: "[System] - Deaktiviere Zigbee Beitritt"
    trigger:
      - entity_id: input_boolean.zigbee_permit_join
        platform: state
        to: 'off'
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.zigbee_permit_join
    action:
      - service: mqtt.publish
        data:
          payload: 'false'
          topic: zigbee2mqtt/bridge/config/permit_join
      - service: timer.cancel
        data:
          entity_id: timer.zigbee_permit_join
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.zigbee_permit_join

